# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50edce94cfaa7b113283a2fe8b78ed045e7efeb6ea0adba0fabd87207e1614618afb9080bcaaa5fee4b1414a3d863a1c1731d86ae6d5276ce44079eff7beb2e6

test:
  secret_key_base: 46c08871ffae411015de872ef1f188b0b9fb4d4a15d5b942cfbf42bff6a5d43b8b2ff12a15c5a9afa4b8c219bc5fdfd3f502b86926bb66b4efd32a0ef53fc854

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
